/// Flutter icons GetMalasIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GetMalasIcons
///      fonts:
///       - asset: fonts/GetMalasIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GetMalasIcons {
  GetMalasIcons._();

  static const _kFontFam = 'GetMalasIcons';

  static const IconData search = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData mala = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe804, fontFamily: _kFontFam);
}
